// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalk.Api.Data;

#nullable disable

namespace NZWalk.Api.Migrations
{
    [DbContext(typeof(NZWalkDBContext))]
    [Migration("20240804192528_Seed Data For Region and Difficulties")]
    partial class SeedDataForRegionandDifficulties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalk.Api.Models.Domain.Difficalty", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("difficalties");

                    b.HasData(
                        new
                        {
                            id = new Guid("4fa8dfb5-2007-40fa-a240-e68d2d34f4f3"),
                            name = "Easy"
                        },
                        new
                        {
                            id = new Guid("3b4d0475-2317-4889-bf97-4fed0a7bcc1c"),
                            name = "Medium"
                        },
                        new
                        {
                            id = new Guid("7c581fc3-2a82-4e2f-9b37-8fc0e1a06279"),
                            name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalk.Api.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regionImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            id = new Guid("bb9add6b-74b9-4803-bcdc-1df37cbee169"),
                            code = "AKL",
                            name = "Auckland",
                            regionImageUrl = "https://pixabay.com/images/search/auckland/"
                        },
                        new
                        {
                            id = new Guid("e3b0c442-98fc-1c14-9af7-1a1768dfefaa"),
                            code = "WLG",
                            name = "Wellington",
                            regionImageUrl = "https://pixabay.com/images/search/wellington/"
                        },
                        new
                        {
                            id = new Guid("6d83e31a-d6b2-4b58-a9be-2d3a5823ff8c"),
                            code = "CHC",
                            name = "Christchurch",
                            regionImageUrl = "https://pixabay.com/images/search/christchurch/"
                        },
                        new
                        {
                            id = new Guid("9d9e2b79-93cb-4a9d-81a6-3a72e3c4b8f2"),
                            code = "HLZ",
                            name = "Hamilton",
                            regionImageUrl = "https://pixabay.com/images/search/hamilton/"
                        },
                        new
                        {
                            id = new Guid("a1f2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6"),
                            code = "DUD",
                            name = "Dunedin",
                            regionImageUrl = "https://pixabay.com/images/search/dunedin/"
                        },
                        new
                        {
                            id = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-f2a3b4c5d6e7"),
                            code = "TRG",
                            name = "Tauranga",
                            regionImageUrl = "https://pixabay.com/images/search/tauranga/"
                        },
                        new
                        {
                            id = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-a3b4c5d6e7f8"),
                            code = "NPE",
                            name = "Napier",
                            regionImageUrl = "https://pixabay.com/images/search/napier/"
                        },
                        new
                        {
                            id = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-b4c5d6e7f8a9"),
                            code = "ROT",
                            name = "Rotorua",
                            regionImageUrl = "https://pixabay.com/images/search/rotorua/"
                        });
                });

            modelBuilder.Entity("NZWalk.Api.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("difficaltyid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("difficltyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("lengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("regionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("walkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("difficaltyid");

                    b.HasIndex("regionId");

                    b.ToTable("walks");
                });

            modelBuilder.Entity("NZWalk.Api.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalk.Api.Models.Domain.Difficalty", "difficalty")
                        .WithMany()
                        .HasForeignKey("difficaltyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalk.Api.Models.Domain.Region", "region")
                        .WithMany()
                        .HasForeignKey("regionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("difficalty");

                    b.Navigation("region");
                });
#pragma warning restore 612, 618
        }
    }
}
